server:
  port: 8083
dubbo:
  application:
    name: web_item
  registry:
    address: zookeeper://192.168.114.128:2181
    protocol:
      port: -1
    consumer:
      check: false
spring:
  rabbitmq:
    host: 192.168.114.128
    username: admin
    password: admin
    port: 5672
    virtual-host: /admin