server:
  port: 8082
dubbo:
  application:
    name: web_search
  registry:
    address: zookeeper://192.168.114.128:2181
  consumer:
    check: false
spring:
  data:
    solr:
      host: http://192.168.114.128:8080/solr